version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "python-stage"
s3_bucket = "python-stage-gh"
s3_prefix = "python-stage"
region = "ap-southeast-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"

